version: '3'

services:

  mariadb:
    image: mariadb
    volumes:
      - ~/data/mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - ~/data/html:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    links:
      - mariadb
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      #- nginx:/etc/nginx/conf.d
      - ~/data/html:/var/www/html
    ports:
      - "443:443"
    links:
      - wordpress
    extra_hosts:
      - "bmaudet.42.fr:127.0.0.1"
    env_file:
      - .env